#!/bin/sh
Host=${1:-fritz.box}
Password=${2}
Username=${3}
ExportPassword=${4:-admin}
Fernzugriff=${5:-0}
SecondPassword=${6}

Now=$(date +"%Y%m%d%H%M%S")
ExportFilename="FritzBox_${Now}.export"

CURL="curl -ksm 20"
# Fuer den Fernzugriff HTTPs und HTTP Auth verwenden
if [ "${Fernzugriff}" = "1" ]; then
	Host="https://${Host}"
	# Fuer den alten Fernzugriff ist HTTP Auth noetig
	CURL="${CURL} -u ${Username}:${Password}"
fi

#Login auf Fritzbox
Login=$($CURL "${Host}/login_sid.lua")
if [ "$?" != "0" -o -z "${Login}" ]; then
	echo "Verbindung zur Fritzbox ${Host} fehlgeschlagen"
	exit 2
elif echo "${Login}" | grep -q "401 Unauthorized (ERR_ACCESS_DENIED)"; then
        echo "Kennwort falsch"
        exit 1
fi

SID=$(echo "${Login}" | sed -n "s|.*<SID>\([0-9a-f]\{16\}\)</SID>.*|\1|p")

if [ -z "${SID}" ]; then
	echo "Unbekannte Fritzbox Version oder falscher Host ${Host} Fehler:"
	echo "${Login}"
	exit 2
elif [ "${SID}" = "0000000000000000" ]; then
	# Unterscheide Boxen vor Fritz!OS 5.50
	if echo "${Login}" | grep -q "<iswriteaccess>"; then
		LoginType=1
		if [ "${Fernzugriff}" = "1" ]; then
			Password="${SecondPassword}"
		fi
	else
		LoginType=2
	fi

	if [ -z "${Password}" ]; then
		echo "Benoetige ein Kennwort!"
		exit 1
	fi

	Challenge=$(echo "${Login}" | sed -n "s|.*<Challenge>\([0-9a-f]\{8\}\)</Challenge>.*|\1|p")
	if [ -z "${Challenge}" ]; then
		echo "Login gibt kein Challenge auf Fritzbox ${Host} zurueck, komisch"
		echo "${Login}"
		exit 2
	fi
	Response=$(printf "${Challenge}-${Password}" | iconv -f utf-8 -t utf-16le | md5 | sed "s| .*||g")


	case "${LoginType}" in
		1) Login=$($CURL -d "login:command/response=${Challenge}-${Response}" -d "getpage=../html/login_sid.xml" "${Host}/cgi-bin/webcm") ;;
		2) Login=$($CURL -d "response=${Challenge}-${Response}" -d "username=${Username}" "${Host}/login_sid.lua") ;;
	esac

	SID=$(echo "${Login}" | sed -n "s|.*<SID>\([0-9a-f]\{16\}\)</SID>.*|\1|p")

	if [ -z "${SID}" ]; then
		echo "Login mit Kennwort gibt keine SID auf Fritzbox ${Host} zurueck, komisch"
		echo "${Login}"
		exit 2
	elif [ "${SID}" = "0000000000000000" ]; then
		echo "Login auf Fritzbox ${Host} fehlgeschlagen. Kennwort falsch?"
		exit 3
	fi
fi


# Download des Konfigurationsbackups
$CURL -fF "sid=${SID}" -F "ImportExportPassword=${ExportPassword}" -F "ConfigExport=" "${Host}/cgi-bin/firmwarecfg" -o "${ExportFilename}"
if [ "$?" != "0" ]; then
	echo "Download des Backups von Fritzbox ${Host} fehlgeschlagen"
	rm -f "${ExportFilename}"
	exit 2
elif ! head -n 1 "${ExportFilename}" | grep -q "^\*\*\*\* FRITZ!Box .* CONFIGURATION EXPORT$"; then
	echo "Download ist kein Backup einer Fritzbox?!"
	rm "${ExportFilename}"
	exit 2
elif ! tail -n 1 "${ExportFilename}" | grep -q "^\*\*\*\* END OF EXPORT .* \*\*\*\*$"; then
	echo "Download ist unvollstaendig"
	rm "${ExportFilename}"
	exit 4
fi


#Logout wenn noetig
case "${LoginType}" in
	2) $CURL -d "security:command/logout=logout" -d "sid=${SID}"  -d "getpage=../html/login_sid.xml" "${Host}/cgi-bin/webcm" -o /dev/null ;;
	1) $CURL -d "logout=logout" -d "sid=${SID}" "${Host}/login_sid.lua" -o /dev/null ;;
esac
